#!/usr/bin/env node
/**
 * Build the static GitHub-Pages playground into docs/.
 *
 * Bundles src/{unicode,dict,decoder,encoder}.js + the tokenize/detokenize
 * portion of the tokenizer into one browser-safe ES module (docs/aicl.js)
 * by rewriting the dict/vocab loading to fetch() calls, and emits docs/
 * index.html + style.css (adapted from playground/) that run fully
 * client-side. GPT/LLaMA comparison needs a tokenizer wasm — the Pages demo
 * therefore shows AICL stage 1/2 and notes the comparison is available in
 * the local server version.
 *
 * Re-run after changing src/ or playground/: node scripts/build_docs.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
mkdirSync(DOCS, { recursive: true });

const read = (p) => readFileSync(join(ROOT, p), 'utf-8');

// ── 1. bundle aicl.js ──────────────────────────────────────────────────────
// unicode.js: as-is (no node imports).
// dict.js: replace fs-backed loadRaw with fetch of JSON files.
// tokenizer: extract tokenize/detokenize/cpToId (skip train + fs load).
let unicodeSrc = read('src/unicode.js');
unicodeSrc = unicodeSrc.replace(/^import .*$/gm, '').replace(/^export \{[^}]*\};?$/gm, '');

const dictSrc = read('src/dict.js')
  .replace(/^import \{ readFileSync \} from 'fs';$/gm, '')
  .replace(/^import \{ join, dirname \} from 'path';$/gm, '')
  .replace(/^import \{ fileURLToPath \} from 'url';$/gm, '')
  .replace(/^import \{ codePoints \} from '\.\/unicode\.js';$/gm, '')
  .replace(/const __dirname = [^;]+;/, '')
  .replace(/const DICT_DIR = [^;]+;/, `
// fs-free dict loading for the browser: primeDict() injects the raw JSON
// objects (fetched by app.js) and the sync loadRaw() serves them to build().
let primed = null;
export function primeDict(raw) { primed = raw; cache = null; }
function loadRaw() {
  if (!primed) throw new Error('dict not primed — call primeDict() first');
  return primed;
}`)
  .replace(/export function loadRaw\(\) \{[\s\S]*?\n\}/, '')
  .replace(/export function dicts\(\) \{[\s\S]*?\n\}/, '');

const encoderSrc = read('src/encoder.js')
  .replace(/^import \{ build \} from '\.\/dict\.js';$/gm, '')
  .replace(/^import \{ codePoints, isPuaCodePoint, ESCAPE_MARKER, requireText \} from '\.\/unicode\.js';$/gm, '');

const decoderSrc = read('src/decoder.js')
  .replace(/^import \{ build, isModifier, getModifierTransform \} from '\.\/dict\.js';$/gm, '')
  .replace(/^import \{ codePoints, isPuaCodePoint, ESCAPE_MARKER, requireText \} from '\.\/unicode\.js';$/gm, '');

// tokenizer: keep only the tokenize/detokenize runtime (no fs, no trainer)
const tokSrc = read('src/tokenizer/index.js');
const tokStart = tokSrc.indexOf('const CP_BASE');
const tokEnd = tokSrc.indexOf('/**\n * Train');
let tokRuntime = tokSrc.slice(tokStart, tokEnd)
  .replace(/^import .*$/gm, '')
  .replace(/export const VOCAB_PATH = .*$/, '')
  .replace(/export function tokenize\(aiclText, vocab = loadTokenizer\(\)\)/, 'export function tokenize(aiclText, vocab)')
  .replace(/export function detokenize\(ids, vocab = loadTokenizer\(\)\)/, 'export function detokenize(ids, vocab)');

tokRuntime += `

export function makeVocab(raw) {
  const merges = new Map(raw.merges.map(([id, rule]) => [id, rule]));
  return {
    merges,
    mergeBase: raw.mergeBase ?? DEFAULT_MERGE_BASE,
    numMerges: raw.numMerges ?? merges.size,
    version: raw.version ?? '1.0',
    maxTokenLength: raw.maxTokenLength ?? 5,
  };
}`;

const bundle = `// AUTO-GENERATED by scripts/build_docs.mjs — do not edit by hand.
// Browser bundle of the AICL encoder/decoder/tokenizer (no Node APIs).
${unicodeSrc}

${dictSrc}

${tokRuntime}

${encoderSrc}

${decoderSrc}
`;
writeFileSync(join(DOCS, 'aicl.js'), bundle);

// ── 2. dict + vocab copies served relative to docs/ ───────────────────────
mkdirSync(join(DOCS, 'dict'), { recursive: true });
for (const f of ['english.json', 'code.json', 'symbols.json', 'modifiers.json']) {
  copyFileSync(join(ROOT, 'dict', f), join(DOCS, 'dict', f));
}
mkdirSync(join(DOCS, 'tokenizer'), { recursive: true });
copyFileSync(join(ROOT, 'tokenizer', 'vocab.json'), join(DOCS, 'tokenizer', 'vocab.json'));

// ── 3. index.html + style.css (adapted from playground/) ──────────────────
let html = read('playground/index.html');
let css = read('playground/style.css');

html = html
  .replace('<title>AICL Playground</title>', '<title>AICL Playground — Live Demo</title>')
  // strip the Upload button + file input (client-side demo keeps Share/hash links)
  .replace('<button id="uploadBtn" class="btn ghost" title="Upload .txt file">Upload</button>', '')
  .replace('<input type="file" id="fileInput" accept=".txt,.md,.js,.json,.sql,.html,.css,.py,.sh" hidden/>', '')
  .replace('<link rel="stylesheet" href="/playground/style.css"/>', '<link rel="stylesheet" href="./style.css"/>')
  // legend must match the client-side bars (Raw÷4 / Raw÷3 estimates + AICL)
  .replace(/<div class="legend">[\s\S]*?<\/div>/, `<div class="legend">
          <span><i class="dot gpt4o"></i> Raw ÷ 4 (≈GPT-4o)</span>
          <span><i class="dot llama"></i> Raw ÷ 3 (≈LLaMA 2)</span>
          <span><i class="dot aicl"></i> AICL</span>
        </div>`)
  .replace('<script type="module" src="/playground/app.js"></script>', '<script type="module" src="./app.js"></script>');

writeFileSync(join(DOCS, 'index.html'), html);
writeFileSync(join(DOCS, 'style.css'), css);

console.log('docs/ built: aicl.js, index.html, style.css, dict/, tokenizer/vocab.json');
